### ISSUE TITLE
卡西米尔晶体有高效合成方法

### ISSUE THREAD

**Issue by WallNutttttts** [yoko008/dyson_sphere_tree#1]
卡西米尔晶体 高效—— 光栅石*6 石墨烯*2 氢*12       4s

**Comment by yoko008** [comment]
啊，大意了，安排上

**Comment by WallNutttttts** [comment]
有机晶体矿安排一下，  建议检查一下所有的高效配方

bugmaker <notifications@github.com> 于 2021年2月25日周四 09:12写道：

**Comment by yoko008** [comment]
都已经安排上了。
检查所有高效配方是不可能滴，这辈子都不可能滴。
因为一个一个对太麻烦了，坐等使用的时候发现。
